# Generated by Django 5.2.9 on 2025-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('productLine', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('textDescription', models.CharField(blank=True, max_length=4000, null=True)),
                ('htmlDescription', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productlines',
            },
        ),
    ]
