# Generated by Django 5.2.9 on 2025-12-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='image',
        ),
    ]
